### ISSUE TITLE
Edge agent support

### ISSUE THREAD

**Issue by tjz101** [lbl8603/vnt#13]
Some devices cannot run third-party programs. But I can add a server next to it as a proxy server. And want to support one to many. Or it can be configured in the router.

**Comment by lbl8603** [comment]
Do the '-i' and '-o' parameters meet your requirements?

**Comment by tjz101** [comment]
> 

It's what I want. Thanks.

**Comment by tjz101** [comment]
> Do the '-i' and '-o' parameters meet your requirements?

It's that I want. Thanks!
