### ISSUE TITLE
win10操作系统启动报错

### ISSUE THREAD

**Issue by pizixi** [lbl8603/vnt#16]
C:\Users\Administrator\Desktop\vnt>vnt-cli.exe -k 123456
version 1.2.3
 ====== Connect Successfully ======
virtual_gateway:10.26.0.1
virtual_ip:10.26.0.5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Custom { kind: Other, error: \"Failed to crate adapter\" }" }', vnt-cli\src\main.rs:346:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lbl8603** [comment]
使用的wintun.dll是什么版本的呢

**Comment by pizixi** [comment]
readme那个下载链接下载的wintun-0.14.1

**Comment by lbl8603** [comment]
系统信息和处理器规格可以提供一下吗

**Comment by pizixi** [comment]
![image](https://github.com/lbl8603/vnt/assets/56673215/580095c7-726d-4f1a-a4f3-0677f7717fc8)

**Comment by lbl8603** [comment]
方便进群或者加好友吗
