### ISSUE TITLE
-W参数运行不久后报错

### ISSUE THREAD

**Issue by ziyouwa** [lbl8603/vnt#17]
1.2.4 ：-W参数说明里面并没有<password>，已尝试-W和-W xxxxx方式，结果都一样。现象是执行一会儿后用vnt-cli --list会报错：
cmd: Resource temporarily unavailable (os error 11)
应该执行任何命令都会报错。

另外，在其中一台linux上用非root用户执行vnt-cli，会创建3个进程，都执行的同样的命令，sudo执行也一样，用root则不会

**Comment by lbl8603** [comment]
不添加-W参数就正常吗。另外建议都用root用户执行命令，不要切换用户

**Comment by ziyouwa** [comment]
不添加-W正常

**Comment by lbl8603** [comment]
看下'uname -a'  的输出

**Comment by ziyouwa** [comment]
我两台linux都一样，
一台gentoo：
Linux xxxxx 6.5.4-gentoo-dist #1 SMP PREEMPT_DYNAMIC Tue Sep 19 15:33:19 -00 2023 x86_64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz GenuineIntel GNU/Linux
一台Debian12：
Linux xxxx 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux

**Comment by lbl8603** [comment]
有其他异常信息吗，除了这些命令不能用以外是否会影响组网通信？ 是否可以开日志，参考[#15 ]

**Comment by ziyouwa** [comment]
好的，稍后尝试

**Comment by ziyouwa** [comment]
![image](https://github.com/lbl8603/vnt/assets/198816/290196cf-0a41-41a5-af2f-969a34a4c705)
感觉并没有多少有用的信息，此时功能貌似不影响，通过10.26.0.0/24网段能互相ping通

**Comment by lbl8603** [comment]
方便进群吗，我给你一个测试程序

**Comment by ziyouwa** [comment]
应该是vnts的问题，换最新的版本后就对了，vnt-cli也换到了1.2.4.2.
