### ISSUE TITLE
在只读文件系统上提示错误，但是使用其他类似软件可以临时创建一个虚拟网卡，vnt则不行

### ISSUE THREAD

**Issue by ycxzfforever** [lbl8603/vnt#30]
1、直接执行
root@imx8mqevk:/opt/ycx-bak/vnt# ./vnt-cli -k 123456
thread 'main' panicked at vnt-cli/src/config/mod.rs:170:42:
called `Result::unwrap()` on an `Err` value: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
2、增加-d参数
root@imx8mqevk:/opt/ycx-bak/vnt# ./vnt-cli -k 123456 -d test
version 1.2.8
 ====== Connect Successfully ======
virtual_gateway:10.26.0.1
virtual_ip:10.26.0.12
 ====== Create Network Interface Successfully ======
name:vnt-tun
version:
 ====== Start Successfully ======
command error :Read-only file system (os error 30)

**Comment by lbl8603** [comment]
下个版本修复这个问题，当前版本要有写程序所在目录的权限

**Comment by ycxzfforever** [comment]
当前目录是具备读写权限的，是否需要读写系统相关的其他文件或目录？

**Comment by lbl8603** [comment]
还要写home目录

**Comment by ycxzfforever** [comment]
> 还要写home目录

好的，谢谢，明白了，期待下个版本修复，幸苦作者了！

**Comment by lbl8603** [comment]
新版本已修复此问题
