### ISSUE TITLE
不指定DNS

### ISSUE THREAD

**Issue by muziling** [lbl8603/vnt#36]
不指定DNS， 默认用114.114.114.114， 有时运营商会干扰，用了第三方的反而会不稳。
没有指定DNS的时候，默认还是用网卡获取到的DNS吧

**Comment by lbl8603** [comment]
你知道怎么获取网卡的DNS吗

**Comment by muziling** [comment]
没有配置DNS参数，就走引入dns这个commit之前的代码逻辑？

**Comment by lbl8603** [comment]
有道理，dns只在某些特定的情况需要自定义

**Comment by lbl8603** [comment]
默认改为使用 223.5.5.5吧

**Comment by muziling** [comment]
国内的DNS都是被污染的，国外的DNS要想正常使用都要科学， 所以不知道这个自定义DNS有啥用处。

**Comment by lbl8603** [comment]
自己搭dns就有用了

**Comment by lbl8603** [comment]
已调整
