### ISSUE TITLE
如何删除已占用的ip

### ISSUE THREAD

**Issue by molezz** [lbl8603/vnt#46]
不知道是不是id还是程序位置移动了，导致同一个机器无法使用希望的ip。显示offline
类似
ubuntu11      10.26.0.23    Offline  
ubuntu11      10.26.0.3

**Comment by lbl8603** [comment]
目前不能主动释放已有IP，可以用如下方式

1.换一个未使用的IP
2.换一个token
3.重启vnts

**Comment by molezz** [comment]
> 目前不能主动释放已有IP，可以用如下方式
> 
> 1.换一个未使用的IP 2.换一个token 3.重启vnts

好吧  先用1 ， 因为用的官方的vnts

**Comment by aogg** [comment]
就不能搞个删除命令吗
