### ISSUE TITLE
Alpine Linux 3.20不能启动

### ISSUE THREAD

**Issue by geekip** [lbl8603/vnt#51]
操作系统：Alpine Linux 3.20.0
_之前在Alpine Linux 3.18上是正常的_

<img width="669" alt="2" src="https://github.com/lbl8603/vnt/assets/4945841/999a1966-5e53-44ab-80c1-683c44a22b44">

**Comment by lmq8267** [comment]
需要sudo？        现在提示No such file or directory 是没有tun的意思    以前提示要好一点，没有tun  没有权限 详细一点  现在的提示看不懂了

**Comment by geekip** [comment]
@lmq8267 root权限运行的

**Comment by geekip** [comment]
忘记初始tun了
echo tun >> /etc/modules
