### ISSUE TITLE
subnet

### ISSUE THREAD

**Issue by steom** [lbl8603/vnt#8]
please consider to add a subnets parameter  

switch-desktop.exe start --subnets 172.11.64.0/22,192.168.1.1/32

so other enabled peers can access the client subnets remote network

**Comment by lbl8603** [comment]
I don't quite understand what you mean. Do you want to visit the machines under the specified network segment?

**Comment by steom** [comment]
Yes exactly

status
Name: Windows 10.0.19045 (Windows 10 Pro) [64-bit]
Virtual ip: 188.0.0.16
Virtual gateway: 188.0.0.1
Virtual netmask: 255.255.0.0
Connection status: Connected
NAT type: Cone
Relay server: xxx.xxx.xxx.xxx:80
Public ips: xxx.xxx.xxx.xxx
Local ip: 10.0.0.2
Subnets: 10.0.0.0/24, 172.11.64.0./22, 192.168.1.1/32

**Comment by lbl8603** [comment]
i'm doing this

**Comment by steom** [comment]
subnets on windows now works with version 1.0.4!

**Comment by lbl8603** [comment]
Yes, it works on linux too. But it has not been tested on mac

**Comment by Droid-MAX** [comment]
can you help me to test armv7 arch pre-compile binaries?

**Comment by steom** [comment]
> Yes, it works on linux too. But it has not been tested on mac

but the configuration is not very user friendly:
the switch-server should have a more active role to route the communication correctly
the peer that expose the subnets, just explicit subnet should suffice, the server already know that peer "local ip"
the peer that use the subnets, just explicit subnets that want to use should suffice, the server already know the "Virtual ip" of remote peers exposing subnets.

**Comment by lbl8603** [comment]
Data routing to which IP, and from which network card sent out, these really need to display configuration

**Comment by lbl8603** [comment]
Do you have any good suggestions

**Comment by steom** [comment]
--out-ip 192.168.10.0/20
the "local ip" from 'status' already is the network card ip to use.

--in-ip 192.168.10.0/20 or -- in-ip ON, 
the "Virtual ip" of 'peers exposings --out-ip' 

the virtual ip of the 'peers that expose the subnets' will be communicated by the switch-server

**Comment by steom** [comment]
> just --out-ip 192.168.10.0/20 the "local ip" from 'status' already indicate the network card ip to use.
> 
> just --in-ip 192.168.10.0/20 (or -- in-ip ON) the "Virtual ip" of the 'peers that expose the subnets' will be communicated by the switch-server

just --out-ip 192.168.10.0/20
the "local ip" from 'status' already indicate the network card ip to use.

just --in-ip 192.168.10.0/20 (or -- in-ip ON)
the "Virtual ip" of the 'peers that expose the subnets' will be communicated by the switch-server

**Comment by steom** [comment]
> Data routing to which IP, and from which network card sent out, these really need to display configuration

just --out-ip 192.168.10.0/20
the "local ip" from 'status' already indicate the network card ip to use.

just --in-ip 192.168.10.0/20 (or -- in-ip ON)
the "Virtual ip" of the 'peers that expose the subnets' will be communicated by the switch-server

**Comment by lbl8603** [comment]
The client may have the same configuration and it is not reasonable to assign it by the server. For“Out IP”, I am here to consider the case of multiple network cards

**Comment by steom** [comment]
also with multiple network cards, only the nic with the default gateway is needed to know for route the subnets

**Comment by steom** [comment]
to expose subnets
Peer (A) syntax: _switch-desktop.exe start --token guid --server 108.177.16.18:7865 --out-ip 192.168.10.0/20_
the switch-server know the "Local Ip" and "Virtual Ip" of peer A.

to use all peers exposed subnets
Peer (B) syntax: _switch-desktop.exe start --token guid --server 108.177.16.18:7865 --in-ip_
the swith-server know all the needed "Virtual Ips" of peers exposing "--out-ip" subnets

or to use only the subnet exposed from Peer (A)
Peer (B) syntax: _switch-desktop.exe start --token guid --server 108.177.16.18:7865 --in-ip 192.168.10.0/20_
the swith-server know the needed "Virtual Ip" of peerA

**Comment by lbl8603** [comment]
good idea!

**Comment by lbl8603** [comment]
Version 1.1.2 simplifies the operation of accessing subnets
